// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/hrabit64/springnote-breezenote/auth"
	"github.com/hrabit64/springnote-breezenote/controller"
	"github.com/hrabit64/springnote-breezenote/middleware"
	"github.com/hrabit64/springnote-breezenote/service"
)

// Injectors from wire.go:

func InitImageController(itemService service.ItemService) controller.ImageController {
	imageController := controller.NewImageController(itemService)
	return imageController
}

func InitAuthMiddleware(client auth.AuthenticateClient) middleware.AuthMiddleware {
	authMiddleware := middleware.NewAuthMiddleware(client)
	return authMiddleware
}
